name: showcase_list_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.2
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^4.0.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  hive_ce_flutter: ^2.3.4
  path_provider: ^2.1.5

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.5

flutter:
  uses-material-design: true
